# Generated by Django 3.2.8 on 2021-10-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_course_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.student'),
        ),
    ]
